# ./docker-compose.yml

version: '3'

services:
  web:
    image: php:7.2.2-apache
    container_name: webtech_web
    volumes:
      - ./php/:/var/www/html/
    ports:
      - "8100:80"
    stdin_open: true
    tty: true
